In [ ]:
import numpy as np

1) Создать двумерный массив с 1 на границе и 0 внутри.

In [ ]:
%%time

rows, cols = 500, 700

array = np.ones((rows, cols), dtype=int)

array[1:rows-1, 1:cols-1] = 0

print(array)

[[1 1 1 ... 1 1 1]
 [1 0 0 ... 0 0 1]
 [1 0 0 ... 0 0 1]
 ...
 [1 0 0 ... 0 0 1]
 [1 0 0 ... 0 0 1]
 [1 1 1 ... 1 1 1]]
CPU times: user 2.89 ms, sys: 0 ns, total: 2.89 ms
Wall time: 2.9 ms


In [ ]:
%%time

array = np.zeros((rows, cols), dtype=int)

for i in range(rows):
    for j in range(cols):
        if i == 0 or i == rows - 1 or j == 0 or j == cols - 1:
            array[i, j] = 1

print(array)

[[1 1 1 ... 1 1 1]
 [1 0 0 ... 0 0 1]
 [1 0 0 ... 0 0 1]
 ...
 [1 0 0 ... 0 0 1]
 [1 0 0 ... 0 0 1]
 [1 1 1 ... 1 1 1]]
CPU times: user 190 ms, sys: 997 µs, total: 191 ms
Wall time: 204 ms


2) Найти индексы ненулевых элементов из [1,2,0,0,4,0].

In [ ]:
lst = [1, 2, 0, 0, 4, 0]

arr = np.array(lst)

nonzero_indexes = np.nonzero(arr)[0]

print(nonzero_indexes)

[0 1 4]


In [ ]:
indices = []

for i in range(len(arr)):
    if arr[i] != 0:
        indices.append(i)

print(indices)

[0, 1, 4]


3) Создайте рандомный вектор и отсортируйте его.

In [ ]:
%%time

size = 10000

vector = np.random.random(size)

sorted_vector = np.sort(vector)

print("Исходный вектор:\n", vector)
print("Отсортированный вектор:\n", sorted_vector)

Исходный вектор:
 [0.30411141 0.46719711 0.58175842 ... 0.87331819 0.77508044 0.95369062]
Отсортированный вектор:
 [8.23358011e-07 2.81528457e-05 3.05262714e-05 ... 9.99770315e-01
 9.99820411e-01 9.99978156e-01]
CPU times: user 6.55 ms, sys: 0 ns, total: 6.55 ms
Wall time: 22.1 ms


In [ ]:
%%time

def quicksort(arr):
    if len(arr) <= 1:
        return arr
    else:
        pivot = arr[0]
        less = [x for x in arr[1:] if x <= pivot]
        greater = [x for x in arr[1:] if x > pivot]
        return np.concatenate((quicksort(less), [pivot], quicksort(greater)))

def babblesort(arr):
    n = len(arr)
    for i in range(n - 1):
        for j in range(n - i - 1):
            if arr[j] > arr[j + 1]:
                arr[j], arr[j + 1] = arr[j + 1], arr[j]
    return arr

sorted_vector = quicksort(vector)
print("Исходный вектор:\n", vector)
print("Отсортированный вектор:\n", sorted_vector)

Исходный вектор:
 [0.30411141 0.46719711 0.58175842 ... 0.87331819 0.77508044 0.95369062]
Отсортированный вектор:
 [8.23358011e-07 2.81528457e-05 3.05262714e-05 ... 9.99770315e-01
 9.99820411e-01 9.99978156e-01]
CPU times: user 51.5 ms, sys: 991 µs, total: 52.5 ms
Wall time: 56.1 ms


4) Дана матрица X и два вектора одинаковой длины i и j. Построить вектор
np.array([X[i[0], j[0]], X[i[1], j[1]], . . . , X[i[N-1], j[N-1]]]). Здесь и далее предполагается, что модуль numpy импортирован под названием np.

In [ ]:
%%time

X = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

i = np.array([0, 1, 2])
j = np.array([1, 2, 0])

result = X[i, j]

print(result)

[2 6 7]
CPU times: user 2.43 ms, sys: 0 ns, total: 2.43 ms
Wall time: 2.44 ms


In [ ]:
%%time

result = []
for coord in zip(i, j):
  result.append(X[coord[0], coord[1]])
print(result)

[2, 6, 7]
CPU times: user 1.05 ms, sys: 0 ns, total: 1.05 ms
Wall time: 1.61 ms


5) Даны два вектора x и y. Проверить, задают ли они одно и то же мультимножество. Для x = np.array([1, 2, 2, 4]), y = np.array([4, 2, 1, 2]) ответ True.

In [ ]:
x = np.array([1, 2, 2, 4])
y = np.array([4, 2, 1, 2])

result = np.array_equal(np.sort(x), np.sort(y))
print(result)
# set(x)==set(y)

True


In [ ]:
def each_count(arr):
    counts = {}
    for value in arr:
        if value in counts:
            counts[value] += 1
        else:
            counts[value] = 1

result = each_count(x) == each_count(y)
print(result)

True


6) Найти максимальный элемент в векторе x среди элементов, перед которыми стоит
нулевой. Для x = np.array([6, 2, 0, 3, 0, 0, 5, 7, 0]) ответ 5.

In [ ]:
x = np.array([6, 2, 0, 3, 0, 0, 5, 7, 0])

zero_indexes = np.where(x == 0)[0]

next_indexes = zero_indexes + 1
next_indexes = next_indexes[next_indexes < len(x)]

filtered_elements = x[next_indexes]

max_element = np.max(filtered_elements)
print(max_element)

5


In [ ]:
cur_max = float("-inf")
for i in range(len(x)-1):
  if x[i] == 0:
    cur_max = max(cur_max, x[i+1])
print(cur_max)

5


7) Реализовать кодирование длин серий (Run-length encoding). Дан вектор x.
Необходимо вернуть кортеж из двух векторов одинаковой длины. Первый содержит
числа, а второй - сколько раз их нужно повторить. Пример: x = np.array([2, 2, 2, 3, 3, 3, 5]). Ответ: (np.array([2, 3, 5]), np.array([3, 3, 1])).

In [ ]:
%%time

def run_length_encoding(x):
    change_indexes = np.where(x[:-1] != x[1:])[0] + 1
    concat = np.concatenate(([0], change_indexes, [len(x)]))
    lengths = np.diff(concat)
    values = x[concat[1:] - 1]
    return values, lengths

def unique_count(x):
    return np.unique(x, return_counts=True)

x = np.array([2, 2, 2, 3, 3, 3, 5, 3])

result = run_length_encoding(x)
print("Кодирование длин:\n", result)

result = unique_count(x)
print("Число уникальных элементов:\n", result)

Кодирование длин:
 (array([2, 3, 5, 3]), array([3, 3, 1, 1]))
Число уникальных элементов:
 (array([2, 3, 5]), array([3, 4, 1]))
CPU times: user 1.2 ms, sys: 0 ns, total: 1.2 ms
Wall time: 1.2 ms


In [ ]:
%%time

numbers = []
counts = []

current_number = None
current_count = 0

def add_current():
    if current_number is not None:
        numbers.append(current_number)
        counts.append(current_count)

for number in x:
    if number == current_number:
        current_count += 1
    else:
        add_current()
        current_number = number
        current_count = 1
add_current()

print(numbers, counts)

[2, 3, 5, 3] [3, 3, 1, 1]
CPU times: user 1.01 ms, sys: 965 µs, total: 1.97 ms
Wall time: 1.97 ms


8) Написать функцию wipe_even(arr, target_value, in_place), принимающую на вход
массив целых чисел arr, и возвращающую массив, полученный из arr путём замены
всех чётных элементов на target_value. Если target_value не указано, то оно должно считаться равным числу 0. Если указан параметр in_place и он равен True, то функция должна менять исходный массив, а если не указан или указан в False, то сохранять его неизменным.

In [ ]:
def wipe_even(arr, target_value=0, in_place=False):
    if not in_place:
        arr = arr.copy()
    arr[np.mod(arr, 2) == 0] = target_value
    return arr

x = np.array([1, 2, 3, 4])
result = wipe_even(x)
print("Зануление в копии:", result)
print("Исходный массив:", x)
wipe_even(x, 9, True)
print("На месте:", x)

Зануление в копии: [1 0 3 0]
Исходный массив: [1 2 3 4]
На месте: [1 9 3 9]


In [ ]:
def wipe_even(arr, target_value=0, in_place=False):
    if not in_place:
        arr = arr.copy()
    for i in range(len(arr)):
        if arr[i] % 2 == 0:
            arr[i] = target_value
    return arr

x = np.array([1, 2, 3, 4])
result = wipe_even(x)
print("Зануление в копии:", result)
print("Исходный массив:", x)
wipe_even(x, 9, True)
print("На месте:", x)

Зануление в копии: [1 0 3 0]
Исходный массив: [1 2 3 4]
На месте: [1 9 3 9]


9) Создайте рандомную матрицу и выполните нормализацию столбцов (из каждого столбца вычесть среднее этого столбца).

In [ ]:
%%time

rows, cols = 3, 5

matrix = np.random.rand(rows, cols)

column_means = np.mean(matrix, axis=0)

normalized_matrix = matrix - column_means

print("Исходная матрица:\n", matrix)
print("Нормализованная матрица:\n", normalized_matrix)

Исходная матрица:
 [[0.23208559 0.89530865 0.96577452 0.87941045 0.89260857]
 [0.49843133 0.36443709 0.47401844 0.31250427 0.15854605]
 [0.6970831  0.67951571 0.62015788 0.51384933 0.3444883 ]]
Нормализованная матрица:
 [[-0.24378108  0.24888817  0.27912424  0.31082244  0.42739426]
 [ 0.02256466 -0.28198339 -0.21263184 -0.25608375 -0.30666826]
 [ 0.22121643  0.03309523 -0.0664924  -0.05473869 -0.12072601]]
CPU times: user 4.66 ms, sys: 997 µs, total: 5.66 ms
Wall time: 7.61 ms


In [ ]:
%%time

for j in range(cols):
    col_sum = 0
    for i in range(rows):
        col_sum += matrix[i, j]

    col_mean = col_sum / rows

    for i in range(rows):
        matrix[i, j] -= col_mean

print("\nНормализованная матрица:")
print(matrix)


Нормализованная матрица:
[[-0.24378108  0.24888817  0.27912424  0.31082244  0.42739426]
 [ 0.02256466 -0.28198339 -0.21263184 -0.25608375 -0.30666826]
 [ 0.22121643  0.03309523 -0.0664924  -0.05473869 -0.12072601]]
CPU times: user 2.29 ms, sys: 0 ns, total: 2.29 ms
Wall time: 2.3 ms


10) Найдите N наибольших значений в векторе.

In [ ]:
def largest_unique_np(arr, n):
    if n == 0:
      return np.empty((0,))
    return np.sort(np.unique(arr))[-n:]

def largest_duplicates_np(arr, n):
    if n == 0:
      return np.empty((0,))
    return np.sort(arr)[-n:]

def largest_unique(arr, n):
    if n == 0:
      return np.empty((0,))
    largest_unique = set()
    for value in arr:
        if len(largest_unique) < n or value > min(largest_unique) :
            largest_unique.add(value)
            if len(largest_unique) > n:
                largest_unique.remove(min(largest_unique))
    result = list(largest_unique)
    result.sort()
    return result

def largest_duplicates(arr, n):
    if n == 0:
      return np.empty((0,))
    largest = [-np.inf] * min(n, arr.size)
    for value in arr:
        if value > largest[0]:
            largest[0] = value
            largest.sort()
    return largest

N = 10
#vector = np.array([0, 2, 4, 2, 1])
vector = np.random.randint(0, 10001, size=999999)

In [ ]:
%%time

print("Используя NumPy:")
unique = largest_unique_np(vector, N)
duplicates = largest_duplicates_np(vector, N)

print("С учетом повторений чисел:", unique)
print("Без учета повторений чисел:", duplicates)

Используя NumPy:
С учетом повторений чисел: [ 9991  9992  9993  9994  9995  9996  9997  9998  9999 10000]
Без учета повторений чисел: [10000 10000 10000 10000 10000 10000 10000 10000 10000 10000]
CPU times: user 167 ms, sys: 6.95 ms, total: 174 ms
Wall time: 180 ms


In [ ]:
%%time

print("Своя реализация:")
unique = largest_unique(vector, N)
duplicates = largest_duplicates(vector, N)

print("С учетом повторений чисел:", unique)
print("Без учета повторений чисел:", duplicates)

Своя реализация:
С учетом повторений чисел: [9991, 9992, 9993, 9994, 9995, 9996, 9997, 9998, 9999, 10000]
Без учета повторений чисел: [10000, 10000, 10000, 10000, 10000, 10000, 10000, 10000, 10000, 10000]
CPU times: user 763 ms, sys: 997 µs, total: 764 ms
Wall time: 769 ms
